name: dolfin_core
description: Core utilities, error handling, network, and storage for Dolfin apps.
version: 1.0.0
publish_to: none
homepage: https://github.com/sifat004bk/dolfin_workspace

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  dolfin_ui_kit:
    path: ../dolfin_ui_kit
  dio: ^5.4.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.3.3
  connectivity_plus: ^6.0.5
  logger: ^2.4.0
  flutter_dotenv: ^5.2.1
  # Added for tour/database/currency features
  path: ^1.9.0
  path_provider: ^2.1.4
  tutorial_coach_mark: ^1.2.11
  flutter_bloc: ^8.1.6
  get_it: ^8.0.2
  currency_picker: ^2.0.21
  url_launcher: ^6.2.5
  flutter_animate: ^4.5.2
  intl: ^0.20.2
  google_fonts: ^6.2.1
  uuid: ^4.5.1
  google_sign_in: ^6.2.2
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  flutter_markdown: ^0.7.4+3
  http_certificate_pinning: ^3.0.1
  sqflite_sqlcipher: ^3.3.0
  local_auth: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mocktail: ^1.0.4
