name: feature_auth
description: Authentication feature package - Login, Signup, Session management.
version: 1.0.0
homepage: https://github.com/sifat004bk/dolfin_workspace

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  dolfin_core:
    path: ../../core/dolfin_core
  dolfin_ui_kit:
    path: ../../core/dolfin_ui_kit
  flutter_bloc: ^8.1.6
  get_it: ^8.0.2
  google_sign_in: ^6.2.1
  firebase_auth: ^5.3.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mocktail: ^1.0.4
  bloc_test: ^9.1.7
