name: feature_chat
description: AI Chat engine - Generic chat interface with configurable persona.
version: 1.0.0
homepage: https://github.com/sifat004bk/dolfin_workspace

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  dolfin_core:
    path: ../../core/dolfin_core
  dolfin_ui_kit:
    path: ../../core/dolfin_ui_kit
  flutter_bloc: ^8.1.6
  get_it: ^8.0.2
  google_generative_ai: ^0.4.6
  flutter_markdown: ^0.7.4+3
  image_picker: ^1.1.2
  record: ^6.1.2
  permission_handler: ^11.3.1
  path_provider: ^2.1.4
  uuid: ^4.5.1
  dartz: ^0.10.1
  sqflite: ^2.3.3+2
  synchronized: ^3.3.1
  fl_chart: ^0.68.0
  data_table_2: ^2.5.15
  flutter_markdown_plus: ^1.0.3



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mocktail: ^1.0.4
  bloc_test: ^9.1.7

flutter:
  assets:
    - assets/icons/
